if (EXISTS "${portable_concurrency_BINARY_DIR}/conanbuildinfo.cmake")
  include("${portable_concurrency_BINARY_DIR}/conanbuildinfo.cmake")
  set(CONAN_CMAKE_FIND_ROOT_PATH ${CONAN_CMAKE_MODULE_PATH})
  conan_basic_setup(TARGETS)
endif()
